---
- name: Update sshd configuration safely, avoid locking yourself out
  template:
    src: sshd_config.j2
    dest: /etc/openssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: Reloaded sshd
  become: true
